"""Exact fields used by selected reproducibility experiments.

Author
------
Shelvean Kapita
Department of Mathematics, Texas A&M University

Date
----
August 2026

The classes in this module are manufactured or elementary exact solutions.  They
are used to prescribe boundary data and to measure numerical error.  They are
kept separate from the adaptive algorithms so that the direction-selection
routines do not have access to the hidden ray information.
"""

from __future__ import annotations

import numpy as np
from scipy.special import hankel1

__author__ = "Shelvean Kapita"
__date__ = "August 2026"


class OutgoingHankel:
    """Outgoing cylindrical wave generated by a source outside the square."""

    def __init__(self, k:
        float, source=(-1.6, 0.3)) -> None:
        self.k = float(k)
        self.source = np.asarray(source, dtype=float)

    def wavenumber(self, y):
        return np.full(np.asarray(y).shape, self.k, dtype=float)

    def __call__(self, x, y):
        radius = np.hypot(
            np.asarray(x) - self.source[0],
            np.asarray(y) - self.source[1],
        )
        return hankel1(0, self.k * radius)


class TransmissionField:
    """Exact two-material plane-wave transmission field across ``y=0``.

    Parameters
    ----------
    omega:
        Base frequency.  The lower and upper wavenumbers are ``omega*n1`` and
        ``omega*n2``.
    incidence_deg:
        Angle of the incident *wave vector* measured from the positive x-axis.
        With the manuscript's ``exp(i omega t)`` convention, this is opposite
        to the physical propagation direction.
    n1, n2:
        Refractive indices below and above the interface.

    Notes
    -----
    The tangential wave number is preserved at the interface.  When it exceeds
    the upper-material wavenumber, the upper normal component is chosen with
    positive imaginary part so that ``exp(i q_y y)`` decays for ``y>0``.
    Continuity of the field and of its normal derivative gives the reflection
    and transmission coefficients.
    """

    def __init__(
        self,
        omega: float,
        incidence_deg: float,
        n1: float = 2.0,
        n2: float = 1.0,
    ) -> None:
        self.omega = float(omega)
        self.incidence_deg = float(incidence_deg)
        self.n1 = float(n1)
        self.n2 = float(n2)
        self._update_wave_data()

    def _update_wave_data(self) -> None:
        theta = np.deg2rad(self.incidence_deg)
        k1 = self.omega * self.n1
        k2 = self.omega * self.n2

        qx = k1 * np.cos(theta)
        qy1 = k1 * np.sin(theta)

        if abs(qx) <= k2:
            qy2 = np.sqrt(k2**2 - qx**2) + 0.0j
        else:
            qy2 = 1j * np.sqrt(qx**2 - k2**2)

        self.q_incident = np.array([qx, qy1], dtype=complex)
        self.q_reflected = np.array([qx, -qy1], dtype=complex)
        self.q_transmitted = np.array([qx, qy2], dtype=complex)

        self.reflection = (qy1 - qy2) / (qy1 + qy2)
        self.transmission = 2.0 * qy1 / (qy1 + qy2)

    def wavenumber(self, y):
        y = np.asarray(y, dtype=float)
        return np.where(y < 0.0, self.omega * self.n1, self.omega * self.n2)

    def __call__(self, x, y):
        x = np.asarray(x)
        y = np.asarray(y)
        points = np.column_stack((x.ravel(), y.ravel()))

        lower = y.ravel() < 0.0
        values = np.empty(len(points), dtype=complex)

        if np.any(lower):
            p = points[lower]
            values[lower] = np.exp(1j * (p @ self.q_incident)) + self.reflection * np.exp(
                1j * (p @ self.q_reflected)
            )

        if np.any(~lower):
            p = points[~lower]
            values[~lower] = self.transmission * np.exp(
                1j * (p @ self.q_transmitted)
            )

        return values.reshape(np.broadcast(x, y).shape)

    def exact_complex_angles(self):
        """Return the analytic lower/lower/upper complex angles for diagnostics."""
        lower = np.array(
            [
                [np.deg2rad(self.incidence_deg), 0.0],
                [np.deg2rad(360.0 - self.incidence_deg), 0.0],
            ]
        )
        qx = self.q_transmitted[0].real
        k2 = self.omega * self.n2
        if abs(qx) <= k2:
            upper = np.array([[np.arccos(qx / k2), 0.0]])
        else:
            upper = np.array([[0.0, np.arccosh(qx / k2)]])
        return lower, upper
