"""Manufactured intrinsic one-form Hodge source on a smooth curved 3-torus.

The finite-element basis, derivatives and moment assembly are imported from
riemannfem; this file computes analytic forcing, loads and error norms.
All numerical outputs are generated by running this script, not manually set.
"""
from __future__ import annotations
import argparse,csv,json,time,os
from pathlib import Path
import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg as spla
from riemannfem.periodic_scalar import periodic_freudenthal_mesh,periodic_tetrahedral_facet_pairings
from riemannfem.entity_assembly import SparseEntityComplex
from riemannfem.torus_metric import AffineTetrahedron,conformal_factor
from riemannfem.bernstein_forms import bernstein_change,reference_differential_bernstein
from riemannfem.reference import simplex_duffy
from riemannfem.forms import wedge_metric_matrix

T=2*np.pi
B_ANISO=np.array([[1.20,.17,.04],[.17,.91,.08],[.04,.08,1.10]])


def analytic_oneform(x,B):
    """Return alpha,dalpha,delta alpha, f=(Delta_H+I)alpha, metric phi.

    alpha_j is a physical chart covector; dalpha is antisymmetric with beta_ij
    and the source uses analytic first and second derivatives, not numerical
    differentiation or a discrete manufactured forcing.
    """
    x=np.atleast_2d(np.asarray(x,float)); nq=len(x)
    C=np.linalg.inv(B)
    phi, gp = conformal_factor(x)
    X,Y,Z=(T*x[:,i] for i in range(3)); S=X+Z
    a=np.zeros((nq,3)); a[:,0]=np.sin(S);a[:,1]=np.cos(X)
    da=np.zeros((nq,3,3)); da[:,0,0]=T*np.cos(S);da[:,2,0]=T*np.cos(S)
    da[:,0,1]=-T*np.sin(X)
    hessa=np.zeros((nq,3,3,3)) # [q,l,i,j] = partial_l partial_i alpha_j
    for l,i in ((0,0),(0,2),(2,0),(2,2)):
        hessa[:,l,i,0]=-T*T*np.sin(S)
    hessa[:,0,0,1]=-T*T*np.cos(X)
    beta=da-da.swapaxes(1,2)
    dbeta=hessa-hessa.swapaxes(2,3) # [q,derivative i, beta index a, beta index b]
    sinX,sinY,sinZ=np.sin(X),np.sin(Y),np.sin(Z)
    cosX,cosY,cosZ=np.cos(X),np.cos(Y),np.cos(Z)
    prod=.12*sinX*sinY*sinZ; co=.08*np.cos(X+Y)
    H=np.zeros((nq,3,3))
    for j in range(3): H[:,j,j]=-T*T*prod
    H[:,0,0]-=T*T*co;H[:,1,1]-=T*T*co
    H[:,0,1]=H[:,1,0]=T*T*(.12*cosX*cosY*sinZ-co)
    H[:,0,2]=H[:,2,0]=T*T*.12*cosX*sinY*cosZ
    H[:,1,2]=H[:,2,1]=T*T*.12*sinX*cosY*cosZ
    # delta alpha = -exp(-2phi) [C_ij partial_i alpha_j + phi_i C_ij alpha_j]
    Sa=np.einsum('ij,qij->q',C,da)+np.einsum('qi,ij,qj->q',gp,C,a)
    sigma=-np.exp(-2*phi)*Sa
    dSa=(np.einsum('ij,qlij->ql',C,hessa)
         +np.einsum('qil,ij,qj->ql',H,C,a)
         +np.einsum('qi,ij,qlj->ql',gp,C,da))
    dsigma=np.exp(-2*phi)[:,None]*(2*gp*Sa[:,None]-dSa)
    # (delta beta)_l = -e^{-2phi} B_lj C_ia C_jb [partial_i beta_ab - phi_i beta_ab]
    derivminus=dbeta-gp[:,:,None,None]*beta[:,None,:,:]
    delta_beta=-np.exp(-2*phi)[:,None]*np.einsum(
        'lj,ia,jb,qiab->ql',B,C,C,derivminus,optimize=True)
    f=a+dsigma+delta_beta
    return a,beta,sigma,f,phi


def validate_source():
    """Independent Euclidean identity check for the trigonometric source."""
    x=np.array([[.17,.28,.39],[.71,.23,.48]])
    B=np.eye(3)
    a,b,sigma,f,phi=analytic_oneform(x,B)
    assert np.max(np.abs(b+b.transpose(0,2,1)))<1e-13
    # Compare f to direct differential expression, using five-point finite
    # differences of delta(alpha) and delta(d alpha) in the physical metric.
    # Formula-level exact derivatives are checked below against central differencing
    # of the codifferential, which does not use the coded analytic Hessians.
    eps=1e-5
    gp0=conformal_factor(x)[1]
    def divergence_oneform(xx):
        aa,_,_,_,_ = analytic_oneform(xx,B)
        # Check a delta identity numerically by differentiating exp(phi) C alpha.
        out=np.zeros(len(xx))
        for i in range(3):
            xplus=xx.copy();xplus[:,i]+=eps
            xminus=xx.copy();xminus[:,i]-=eps
            def weighted(xx):
                ff,_=conformal_factor(xx)
                vv=np.zeros_like(xx)
                vv[:,0]=np.sin(T*(xx[:,0]+xx[:,2])); vv[:,1]=np.cos(T*xx[:,0])
                return np.exp(ff)*vv[:,i]
            out+=(weighted(xplus)-weighted(xminus))/(2*eps)
        return -np.exp(-3*conformal_factor(xx)[0])*out
    num=divergence_oneform(x)
    assert np.max(np.abs(num-sigma))<1e-6,(num,sigma)


def ref_values(C,r,q):
    lam,w=simplex_duffy(3,q); pts=lam[:,1:]
    from riemannfem.bernstein_forms import bernstein_change
    val=[]
    for k in (0,1,2):
        Bk=bernstein_change(3,r,k)[0]
        Vk=C.spaces[k]
        val.append(np.asarray([Bk.T@Vk.values(x) for x in pts]))
    return pts,w,val


def local_and_rhs(C,cells,N,r,B,q):
    pts,w,vs=ref_values(C,r,q)
    v0=vs[0][:,:,0];v1=vs[1];v2=vs[2]
    wedges=[(0,1),(0,2),(1,2)]
    local=[[],[],[]]; local_rhs=[]
    detB=np.sqrt(np.linalg.det(B)); Binv=np.linalg.inv(B)
    for ci,V in enumerate(cells):
        cell=AffineTetrahedron(V/N); E=cell.E; Ei=np.linalg.inv(E)
        physical=cell.physical_coordinates(pts)
        aa,bb,ss,ff,phi=analytic_oneform(physical,B)
        jac=abs(np.linalg.det(E))*detB
        G0inv=Ei@Binv@Ei.T
        H2=wedge_metric_matrix(G0inv,2)
        ww=w*jac
        wm=ww*np.exp(3*phi); w1=ww*np.exp(phi); w2=ww*np.exp(-phi)
        M0=v0.T@(wm[:,None]*v0)
        M1=np.einsum('q,qai,ij,qbj->ab',w1,v1,G0inv,v1,optimize=True)
        M2=np.einsum('q,qai,ij,qbj->ab',w2,v2,H2,v2,optimize=True)
        local[0].append(M0);local[1].append(M1);local[2].append(M2)
        fref=ff@E
        rhs=np.einsum('q,qai,ij,qj->a',w1,v1,G0inv,fref,optimize=True)
        local_rhs.append(rhs)
    masses=[C.assemble_mass(k,local[k],local_basis='bernstein') for k in range(3)]
    Ein=C.Einv[1]; nb=C.spaces[1].nloc
    broken=np.concatenate([Ein.T@l for l in local_rhs])
    F=C.P[1].T@broken
    return masses,np.asarray(F).ravel()


def errors(C,cells,N,r,B,alpha_global,sigma_global,q):
    pts,w,vs=ref_values(C,r,q)
    v0=vs[0][:,:,0]; v1=vs[1];v2=vs[2]
    Dref=reference_differential_bernstein(3,r,1)
    Binv=np.linalg.inv(B);detB=np.sqrt(np.linalg.det(B))
    nb0=C.spaces[0].nloc; nb1=C.spaces[1].nloc
    loc0=(C.P[0]@sigma_global).reshape(len(cells),nb0)@C.Einv[0].T
    loc1=(C.P[1]@alpha_global).reshape(len(cells),nb1)@C.Einv[1].T
    mass_err=d_err=sigma_err=mass_ref=d_ref=sigma_ref=0.
    for ci,V in enumerate(cells):
        cell=AffineTetrahedron(V/N);E=cell.E;Ei=np.linalg.inv(E)
        aa,bb,ss,ff,phi=analytic_oneform(cell.physical_coordinates(pts),B)
        det0=abs(np.linalg.det(E))*detB
        ww=w*det0;wm=ww*np.exp(3*phi);w1=ww*np.exp(phi);w2=ww*np.exp(-phi)
        G0inv=Ei@Binv@Ei.T;H2=wedge_metric_matrix(G0inv,2)
        ah=v1.transpose(0,2,1)@loc1[ci] # [q, n_coord_1] (matmul)
        a_exact=aa@E
        diff=a_exact-ah
        mass_err+=np.einsum('q,qi,ij,qj->',w1,diff,G0inv,diff,optimize=True)
        mass_ref+=np.einsum('q,qi,ij,qj->',w1,a_exact,G0inv,a_exact,optimize=True)
        dh=v2.transpose(0,2,1)@(Dref@loc1[ci])
        beta_ref=np.einsum('ai,qab,bj->qij',E,bb,E,optimize=True)
        be=np.column_stack([beta_ref[:,i,j] for i,j in ((0,1),(0,2),(1,2))])
        diff=be-dh
        d_err+=np.einsum('q,qi,ij,qj->',w2,diff,H2,diff,optimize=True)
        d_ref+=np.einsum('q,qi,ij,qj->',w2,be,H2,be,optimize=True)
        sh=v0@loc0[ci]
        sigma_err+=np.dot(wm,(sh-ss)**2);sigma_ref+=np.dot(wm,ss**2)
    return {
      'L2_1_error':float(np.sqrt(mass_err)),'d_1_error':float(np.sqrt(d_err)),
      'delta_aux_error':float(np.sqrt(sigma_err)),
      'relative_L2_1':float(np.sqrt(mass_err/mass_ref)),
      'relative_d_1':float(np.sqrt(d_err/d_ref)),
      'relative_delta_aux':float(np.sqrt(sigma_err/sigma_ref)),
    }


def solve_mixed(M, F, D0, D1, method='schur', rtol=2e-11, maxiter=600):
    """Solve the correct mixed Hodge--Laplace weak system.

       -M0 sigma + D0.T M1 alpha = 0,
        M1 D0 sigma + (M1+D1.T M2 D1) alpha = F.

    'schur' eliminates sigma and solves an SPD problem with CG.  Its
    matrix action applies M0^-1 by sparse factorization; the preconditioner
    applies A^-1 by sparse factorization.  Neither inverse is made dense.
    'direct' solves the full sparse mixed system; useful as an audit.
    """
    M0,M1,M2=M
    A=(D1.T@M2@D1+M1).tocsc()
    B=(M1@D0).tocsc()
    if method=='direct':
        K=sp.bmat([[-M0.tocsc(),B.T],[B,A]],format='csc')
        rhs=np.r_[np.zeros(M0.shape[0]),F]
        x=spla.spsolve(K,rhs)
        residual=float(np.linalg.norm(K@x-rhs)/max(1.,np.linalg.norm(rhs)))
        return np.asarray(x[:M0.shape[0]]),np.asarray(x[M0.shape[0]:]),residual,0
    if method!='schur':
        raise ValueError('solver must be direct or schur')
    fac0=spla.splu(M0.tocsc())
    facA=spla.splu(A)
    Btr=B.T.tocsr()
    n=M1.shape[0]
    def mv(x):
        return A@x + B@fac0.solve(Btr@x)
    Sop=spla.LinearOperator((n,n),matvec=mv,dtype=np.float64)
    Pop=spla.LinearOperator((n,n),matvec=facA.solve,dtype=np.float64)
    calls=[0]
    def cb(x):calls[0]+=1
    alpha,info=spla.cg(Sop,F,M=Pop,rtol=rtol,atol=0.,maxiter=maxiter,callback=cb)
    if info:
        raise RuntimeError(f'Schur CG did not converge: info={info}, iter={calls[0]}; '
                           'retry --solver direct or relax --rtol')
    sigma=fac0.solve(Btr@alpha)
    eq0=-M0@sigma+Btr@alpha
    eq1=B@sigma+A@alpha-F
    residual=float(np.linalg.norm(np.r_[eq0,eq1])/max(1.,np.linalg.norm(F)))
    return sigma,alpha,residual,calls[0]


def run(N,r,anisotropic=False,q=None,error_q=None,solver='schur',rtol=2e-11,
        maxiter=600,assert_residual=5e-8):
    t0=time.perf_counter()
    B=B_ANISO.copy() if anisotropic else np.eye(3)
    cells=periodic_freudenthal_mesh(N)
    pairs=periodic_tetrahedral_facet_pairings(cells,N)
    C=SparseEntityComplex(len(cells),r,pairs,reference_basis='bernstein')
    q=int(q or max(6,r+4))
    error_q=int(error_q or q+2)
    if error_q<q:
        raise ValueError('error quadrature should be at least solve quadrature')
    M,F=local_and_rhs(C,cells,N,r,B,q)
    D0,D1=C.D[:2]
    sig,alpha,residual,niter=solve_mixed(M,F,D0,D1,method=solver,
                                         rtol=rtol,maxiter=maxiter)
    if not np.isfinite(residual) or residual>assert_residual:
        raise RuntimeError(f'mixed residual {residual:.3e} exceeds {assert_residual:.3e}')
    err=errors(C,cells,N,r,B,alpha,sig,error_q)
    result=dict(N=N,r=r,p=r,metric='anisotropic' if anisotropic else 'isotropic',
       cells=len(cells),dofs_0=M[0].shape[0],dofs_1=M[1].shape[0],
       quad=q,error_quad=error_q,solver=solver,iterations=int(niter),**err,
       residual=float(residual),d2=float(max(C.d2_defects)),
       seconds=round(time.perf_counter()-t0,2))
    print(json.dumps(result),flush=True)
    return result

if __name__=='__main__':
    parser=argparse.ArgumentParser(description='High-order intrinsic 1-form Hodge--Laplace FEM')
    parser.add_argument('--N',type=int,default=3,help='periodic subdivisions per coordinate')
    parser.add_argument('--p','--r',dest='r',type=int,default=4,
                        help='FEEC order: P_p^- Lambda^k (p=3,4,5 recommended)')
    parser.add_argument('--anisotropic',action='store_true')
    parser.add_argument('--quad',type=int,default=None)
    parser.add_argument('--error-quad',type=int,default=None)
    parser.add_argument('--solver',choices=['schur','direct'],default='schur')
    parser.add_argument('--rtol',type=float,default=2e-11)
    parser.add_argument('--maxiter',type=int,default=600)
    parser.add_argument('--results',default='results/oneform.jsonl')
    args=parser.parse_args()
    if args.N<2 or args.r<1:parser.error('N>=2 and p>=1 required')
    validate_source()
    result=run(args.N,args.r,args.anisotropic,args.quad,args.error_quad,
               solver=args.solver,rtol=args.rtol,maxiter=args.maxiter)
    path=Path(args.results);path.parent.mkdir(exist_ok=True,parents=True)
    with path.open('a',encoding='utf8') as fp:fp.write(json.dumps(result)+'\n')
